---
version: "3.9"
services:
    web:
        image: nginx
        restart: always
        ports:
          - 8080:80
        volumes:
          - ./config:/etc/nginx/conf.d
          - ./content:/tmp/content
...
