---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.101.47/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 9.9.9.9
      routes:
        - to: 0.0.0.0/0
          via: 192.168.101.1
    eth1:
      addresses:
        - 10.34.40.43/24
      routes:
        - to: 10.0.0.0/8
          via: 10.34.40.1
        - to: 232.0.0.0/8
          scope: link
        - to: 237.0.0.0/8
          scope: link
        - to: 238.0.0.0/8
          scope: link
        - to: 239.0.0.0/8
          scope: link
...

