---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.101.46/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 9.9.9.9
      routes:
        - to: 0.0.0.0/0
          via: 192.168.101.1
    eth1: {}
    eth2: {}
  bonds:
    bond0:
      interfaces:
        - eth1
        - eth2
      addresses:
        - 192.168.30.46/24
        - fc00:192:168:30::46/64
      parameters:
        mode: 802.3ad
      routes:
        - to: 192.168.0.0/16
          via: 192.168.30.1
        - to: fc00:192:168::/48
          via: fc00:192:168:30::1
...

