---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.101.47/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 9.9.9.9
      routes:
        - to: 0.0.0.0/0
          via: 192.168.101.1
    eth1:
      addresses:
        - 192.168.20.47/24
        - fc00:192:168:20::47/64
      routes:
        - to: 192.168.0.0/16
          via: 192.168.20.1
        - to: fc00:192:168::/48
          via: fc00:192:168:20::1
...

